//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Model.HRMS.Settings
{
    using QueryGenerator;
    using System;
    using System.Collections.Generic;

    [Table("CountryCode", "Settings")]
    public partial class CountryCode
    {
        [PKey]
        public int ID { get; set; }
        public string ISO { get; set; }
        public string Name { get; set; }
        public string NiceName { get; set; }
        public string ISO3 { get; set; }
        public Nullable<int> NumCode { get; set; }
        public Nullable<int> PhoneCode { get; set; }
    }
}
