//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Model.HRMS.Settings
{
    using QueryGenerator;
    using System;
    using System.Collections.Generic;

    [Table("Menu", "Settings")]
    public partial class Menu
    {
        [PKey]
        public int MenuId { get; set; }
        public string Route { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Icon { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
