//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Model.HRMS.Settings
{
    using QueryGenerator;
    using System;
    using System.Collections.Generic;

    [Table("OrganizationProfile", "Settings")]
    public partial class OrganizationProfile
    {
        [PKey]
        public int OrgId { get; set; }
        public string OrgName { get; set; }
        public int OrgType { get; set; }
        public string RegistrationNo { get; set; }
        public string ContactNo { get; set; }
        public string LoginId { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string LandLine { get; set; }
        public string TradingName { get; set; }
        public string TradingPeriod { get; set; }
        public Nullable<int> NameOfSector { get; set; }
        public Nullable<bool> ChangedTrading { get; set; }
        public Nullable<bool> FacedPenalty { get; set; }
        public string LogoURL { get; set; }
        public string PostCode { get; set; }
        public string AddressLineOne { get; set; }
        public string AddressLineTwo { get; set; }
        public string AddressLineThree { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
