//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Model.HRMS.Settings
{
    using QueryGenerator;
    using System;
    using System.Collections.Generic;

    [Table("OrgAuthoriseOrKeyPerson", "Settings")]
    public partial class OrgAuthoriseOrKeyPerson
    {
        [PKey]
        public int SL { get; set; }
        public int OrgId { get; set; }
        public int EmployeeId { get; set; }
        public string ProofOfId { get; set; }
        public Nullable<bool> HistoryOfCriminalConvictionBankruptcy { get; set; }
        public bool KeyContact { get; set; }
        public bool LevelOneUser { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
