//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Model.HRMS.Recruitment
{
    using QueryGenerator;
    using System;
    using System.Collections.Generic;

    [Table("JobApplicationDetails", "Recruitment")]
    public partial class JobApplicationDetails
    {
        [PKey]
        public int JobId { get; set; }
        public int OrgId { get; set; }
        public string EmployeeCode { get; set; }
        public int StageOfApplication { get; set; }
        public int ApplicationChannel { get; set; }
        public Nullable<int> ApplicationStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
