//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Model.HRMS.Emp
{
    using QueryGenerator;
    using System;
    using System.Collections.Generic;

    [Table("EmployeeAddress", "Emp")]
    public partial class EmployeeAddress
    {
        [PKey]
        public string EmployeeCode { get; set; }
        public int InstituteId { get; set; }
        public int AddressTypeId { get; set; }
        public string PostCode { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public int City { get; set; }
        public int Country { get; set; }
        public int AddedByUserId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
