//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Model.HRMS.Security
{
    using QueryGenerator;
    using System;
    using System.Collections.Generic;

    [Table("Screen", "Security")]
    public partial class Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Screen()
        {
            this.RoleWiseScreenPermissions = new HashSet<RoleWiseScreenPermission>();
        }
    
        [PKey]
        public int ScreenCode { get; set; }

        public string ScreenName { get; set; }

        public int OrgId { get; set; }

        public int ModuleId { get; set; }

        public int SubModuleId { get; set; }

        public int SectionId { get; set; }

        public int ScreenOrder { get; set; }

        public string URL { get; set; }

        public string ControllerName { get; set; }

        public string ActionName { get; set; }

        public string Description { get; set; }
        public bool IsActive { get; set; }

        public int CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public int? UpdatedBy { get; set; }

        public DateTime? UpdatedDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleWiseScreenPermission> RoleWiseScreenPermissions { get; set; }
    }
}
