//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Model.HRMS.Security
{
    using QueryGenerator;
    using System;
    using System.Collections.Generic;

    [Table("SubModuleSections", "Security")]
    public partial class SubModuleSections
    {
        [PKey]
        public int SectionId { get; set; }

        public string SectionName { get; set; }

        public int InstituteId { get; set; }

        public int ModuleId { get; set; }

        public int SubModuleId { get; set; }

        public string IconName { get; set; }

        public int SectionOrder { get; set; }

        public bool IsActive { get; set; }

        public int AddedByUserId { get; set; }

        public DateTime AddedDate { get; set; }

        public int? UpdatedByUserId { get; set; }

        public DateTime? UpdatedDate { get; set; }
    }
}
